### ISSUE TITLE
[SOLVED] Viewer is not loading glb files correctly

### ISSUE THREAD

**Issue by rodrix385** [BabylonJS/Editor#53]
Glb and babylon files exported from 3ds Studio Max are not imported correctly.
Faces are "flipped". Lighting is happening on interior faces of mesh. Exterior faces are being "back culled".
Very strange.

Related to this issue: https://github.com/BabylonJS/Exporters/issues/132#issuecomment-378817573
The issue is twice (once here and once on the exporter) since there are actually 2 issues (or mulitple concurring bugs).

ThreeJS importer can read the non-working GLB file just fine, so that confirms there is a bug on the Editor.  

@deltakosh

**Comment by julien-moreau** [comment]
Thanks for reporting! Just fixed by updating the loaders with file https://www.dropbox.com/s/ybtkxp3ia9xb5tj/test2.glb?dl=0
@deltakosh

Deploying asap on editor.babylonjs.com

**Comment by julien-moreau** [comment]
Deployed! Can you confirm that it now works ?
Thanks!

**Comment by rodrix385** [comment]
Thank you so much!
I have tested the same file, and I think I see a change, but I can still "see-through" the object.

It seems there is a bug ALSO on the 3ds Max Babylon exporter too since it seems to be exporting with BLEND as I can see through the object when it should be solid.
![image](https://user-images.githubusercontent.com/26559703/38383346-ad2a1f4a-38e2-11e8-9695-ef6bb84a83c1.png)

What do you think the issue is? Thanks so much.
On the other hand, ThreeJS displays the SAME model perfectly: https://gltf-viewer.donmccurdy.com/

So I am not sure. I guess still not fixed?

**Comment by rodrix385** [comment]
Even with this OBJ file I am getting the same issue:
![image](https://user-images.githubusercontent.com/26559703/38383626-65c9751e-38e3-11e8-8fe6-01799f4a66fa.png)

OBJ file (800kb)
https://www.dropbox.com/s/uvutme8yc2vpcy5/test.obj?dl=0

I guess there is still an issue with the editor?

**Comment by julien-moreau** [comment]
According to your obj file, if you set a standard material and disable back face culling on it, you get the good result: you cannot see through the object.

Still digging into the problem

**Comment by julien-moreau** [comment]
Can you also provide the MTL file ?
Thanks!

**Comment by rodrix385** [comment]
[test.mtl.txt](https://github.com/BabylonJS/Editor/files/1881952/test.mtl.txt)
Sure! Here you.

That's actually the problem, the faces are "flipped". Disabling back face culling shouldn't be necessary.
To begin, faces should not be flipped in the first place...

**Comment by julien-moreau** [comment]
Just exported cubes from 3ds Max by unchecking only "Relative numbers" and it works
Did you use the gw::OBJ-Exporter ?

**Comment by julien-moreau** [comment]
Just imported your obj file into 3ds Max and tried to export as .babylon, obj, gltf and glb
All result the same :(

Are you sure that your model is 100% correct? I’m not an artist and a 3ds Max user :)

**Comment by rodrix385** [comment]
Yes, I am pretty sure the model is correct...
I can tell you one thing, with my recents tests, if I export via gltf, and then delete manually BLEND from the gltf the file gets loaded correctly.

The conclusion I get from the other thread is the following. There are 2 bugs:
Bug 1) The Exporter has a bug. It sometimes exports the gltf with BLEND when it shouldn't.
BUg 2) The Editor has a bug. If the gltf has BLEND it doesn't detect it. If detected,  depth pre-pass should be enabled.

**Comment by deltakosh** [comment]
bug 1: I'll check with @noalak
bug2: not a bug as I mentioned earlier: Depth pre-pass msut not be by default. It depends on the mesh.

**Comment by deltakosh** [comment]
Cam you share the original max file to help us detect why we export with Blend enabled

**Comment by rodrix385** [comment]
>> bug2: not a bug as I mentioned earlier: Depth pre-pass must not be by default. It depends on the mesh.
Then I suggest that the Editor has an option to manually enable depth pre-pass, and if that solves the issue, this thread should be closed on the Editor end and continue open on the export end.

About the original Max file, here you go:
[Piano Frame.zip](https://github.com/BabylonJS/Editor/files/1887838/Piano.Frame.zip)

**Comment by deltakosh** [comment]
Agree for the option!

**Comment by julien-moreau** [comment]
Adding the option :)

**Comment by rodrix385** [comment]
Awesome :+1:  :)

**Comment by julien-moreau** [comment]
Adding the option and deploying ASAP :)

**Comment by julien-moreau** [comment]
Deployed!
I suggest that you use the V2 of the editor here: http://editor.babylonjs.com/v2/
Once you edit a material, go to the "Options" folder and check "Need Depth Pre Pass"

**Comment by rodrix385** [comment]
Amazing!
@julien-moreau , I also wanted to take the time to tell you that the V2 version of the editor is looking absolutely STUNNING! Thanks so much for putting so much work into this. It is looking absolutely fantastic!!! :)

**Comment by julien-moreau** [comment]
Thanks ! Happy that you like it ! Will release a new update soon with new layout features

Closing the issue :)
